### ISSUE TITLE
Linkdagi href="" qiymatini to'g'rilab qo'yish kerak

### ISSUE THREAD

**Issue by ShokhrukhTurgunov** [OzodaKhamdamova/classic-food-delivery#1]
<li class="info-item tel"><a class="info-link-tel" href="tel" >0 800 33 08 98</a></li>

href="" ichiga href="tel:0 800 33 08 98" qilib qo'ysangiz bo'ladi.

**Comment by OzodaKhamdamova** [comment]
corrected
